### ISSUE TITLE
[Errno 2] No such file or directory: 'freetype-2.6.3.tar.gz'

### ISSUE THREAD

**Issue by ghost** [lasote/conan-freetype#6]
Hi @lasote,

I seem to be having this problem in all my builds, which crash while retrieving freetype:

https://travis-ci.org/dimi309/small3d/jobs/175746477

It wasn't the case yesterday... Did something change?

Thanks

**Comment by lasote** [comment]
Hi! no changes on my side, maybe the source zip is missing or something. Let me check it.

**Comment by lasote** [comment]
I really don't know what is happening but I suspect it is a travis networking issue. (Some of my boost builds are failing too with the same reason)
Is ok building it in local. Please, let's wait some hours and let me know if it's still failing.

Thanks @dimi309!

**Comment by ghost** [comment]
No rush, I'll check again tomorrow morning and report back :)

**Comment by ghost** [comment]
It's working again. Who knows what happened...

https://ci.appveyor.com/project/coding3d/small3d/build/job/mc7gmdx7qhdiq85m
